/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 dungeon.glb -T
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export default function Dungeon(props) {
  const { nodes} = useGLTF("/dungeon-transformed.glb");
  const texture = useTexture("/baked.jpg");
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;
  texture.colorSpace = THREE.SRGBColorSpace;
  const mat = new THREE.MeshBasicMaterial({ map: texture });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      <mesh geometry={nodes.Cube001.geometry} material={mat} />
      <mesh geometry={nodes.Cube002.geometry} material={mat} />
      <mesh geometry={nodes.Cube003.geometry} material={mat} />
      <mesh geometry={nodes.Cube004.geometry} material={mat} />
      <mesh geometry={nodes.Cube005.geometry} material={mat} />
      <mesh geometry={nodes.Cube006.geometry} material={mat} />
      <mesh geometry={nodes.Cube007.geometry} material={mat} />
      <mesh geometry={nodes.Cube009.geometry} material={mat} />
      <mesh geometry={nodes.Cube011.geometry} material={mat} />
      <mesh geometry={nodes.Cube012.geometry} material={mat} />
      <mesh geometry={nodes.Cube015.geometry} material={mat} />
      <mesh geometry={nodes.Cube016.geometry} material={mat} />
      <mesh geometry={nodes.Cube017.geometry} material={mat} />
      <mesh geometry={nodes.Cube020.geometry} material={mat} />
      <mesh geometry={nodes.Cube021.geometry} material={mat} />
      <mesh geometry={nodes.Cube023.geometry} material={mat} />
      <mesh geometry={nodes.Cube025.geometry} material={mat} />
      <mesh geometry={nodes.Cube026.geometry} material={mat} />
      <mesh geometry={nodes.Cube028.geometry} material={mat} />
      <mesh geometry={nodes.Cube029.geometry} material={mat} />
      <mesh geometry={nodes.Cube032.geometry} material={mat} />
      <mesh geometry={nodes.Cube033.geometry} material={mat} />
      <mesh geometry={nodes.Cube034.geometry} material={mat} />
      <mesh geometry={nodes.Cube035.geometry} material={mat} />
      <mesh geometry={nodes.Cube036.geometry} material={mat} />
      <mesh geometry={nodes.Cube037.geometry} material={mat} />
      <mesh geometry={nodes.Cube038.geometry} material={mat} />
      <mesh geometry={nodes.Cube039.geometry} material={mat} />
      <mesh geometry={nodes.Cube040.geometry} material={mat} />
      <mesh geometry={nodes.Cube042.geometry} material={mat} />
      <mesh geometry={nodes.Cube043.geometry} material={mat} />
      <mesh geometry={nodes.Cube047.geometry} material={mat} />
      <mesh geometry={nodes.Cube050.geometry} material={mat} />
      <mesh geometry={nodes.Cube051.geometry} material={mat} />
      <mesh geometry={nodes.Cube052.geometry} material={mat} />
      <mesh geometry={nodes.Cube054.geometry} material={mat} />
      <mesh geometry={nodes.Cube055.geometry} material={mat} />
      <mesh geometry={nodes.Cube056.geometry} material={mat} />
      <mesh geometry={nodes.Cube058.geometry} material={mat} />
      <mesh geometry={nodes.Cube059.geometry} material={mat} />
      <mesh geometry={nodes.Cube060.geometry} material={mat} />
      <mesh geometry={nodes.Cube062.geometry} material={mat} />
      <mesh geometry={nodes.Cube063.geometry} material={mat} />
      <mesh geometry={nodes.Cube008.geometry} material={mat} />
      <mesh geometry={nodes.Cube014.geometry} material={mat} />
      <mesh geometry={nodes.Cube013.geometry} material={mat} />
      <mesh geometry={nodes.Cube057.geometry} material={mat} />
      <mesh geometry={nodes.Cube061.geometry} material={mat} />
      <mesh geometry={nodes.Cube024.geometry} material={mat} />
      <mesh geometry={nodes.Cube064.geometry} material={mat} />
      <mesh geometry={nodes.Cube065.geometry} material={mat} />
      <mesh geometry={nodes.Cube066.geometry} material={mat} />
      <mesh geometry={nodes.Cube067.geometry} material={mat} />
      <mesh geometry={nodes.Cube068.geometry} material={mat} />
      <mesh geometry={nodes.Cube069.geometry} material={mat} />
      <mesh geometry={nodes.Cube084.geometry} material={mat} />
      <mesh geometry={nodes.Cube085.geometry} material={mat} />
      <mesh geometry={nodes.Cube086.geometry} material={mat} />
      <mesh geometry={nodes.Cube087.geometry} material={mat} />
      <mesh geometry={nodes.Cube088.geometry} material={mat} />
      <mesh geometry={nodes.Cube089.geometry} material={mat} />
      <mesh geometry={nodes.Cube090.geometry} material={mat} />
      <mesh geometry={nodes.Cube091.geometry} material={mat} />
      <mesh geometry={nodes.Cube092.geometry} material={mat} />
      <mesh geometry={nodes.Cube093.geometry} material={mat} />
      <mesh geometry={nodes.Cube044.geometry} material={mat} />
      <mesh geometry={nodes.Cube045.geometry} material={mat} />
      <mesh geometry={nodes.Cube046.geometry} material={mat} />
      <mesh geometry={nodes.Cube073.geometry} material={mat} />
      <mesh geometry={nodes.Cube074.geometry} material={mat} />
      <mesh geometry={nodes.Cube075.geometry} material={mat} />
      <mesh geometry={nodes.Cube076.geometry} material={mat} />
      <mesh geometry={nodes.Cube077.geometry} material={mat} />
      <mesh geometry={nodes.Cube078.geometry} material={mat} />
      <mesh geometry={nodes.Cube079.geometry} material={mat} />
      <mesh geometry={nodes.Cube080.geometry} material={mat} />
      <mesh geometry={nodes.Cube081.geometry} material={mat} />
      <mesh geometry={nodes.Cube082.geometry} material={mat} />
      <mesh geometry={nodes.Cube083.geometry} material={mat} />
      <mesh geometry={nodes.Cube094.geometry} material={mat} />
      <mesh geometry={nodes.Cube095.geometry} material={mat} />
      <mesh geometry={nodes.Cube096.geometry} material={mat} />
      <mesh geometry={nodes.Cube097.geometry} material={mat} />
      <mesh geometry={nodes.Cube098.geometry} material={mat} />
      <mesh geometry={nodes.Cube099.geometry} material={mat} />
      <mesh geometry={nodes.Cube100.geometry} material={mat} />
      <mesh geometry={nodes.Cube101.geometry} material={mat} />
      <mesh geometry={nodes.Cube103.geometry} material={mat} />
      <mesh geometry={nodes.Cube105.geometry} material={mat} />
      <mesh geometry={nodes.Cube106.geometry} material={mat} />
      <mesh geometry={nodes.Cube109.geometry} material={mat} />
      <mesh geometry={nodes.Cube112.geometry} material={mat} />
      <mesh geometry={nodes.Cube108.geometry} material={mat} />
      <mesh geometry={nodes.Cube010.geometry} material={mat} />
      <mesh geometry={nodes.Cube018.geometry} material={mat} />
      <mesh geometry={nodes.Cube030.geometry} material={mat} />
      <mesh geometry={nodes.Cube031.geometry} material={mat} />
      <mesh geometry={nodes.Cube041.geometry} material={mat} />
      <mesh geometry={nodes.Cube072.geometry} material={mat} />
      <mesh geometry={nodes.Cube116.geometry} material={mat} />
      <mesh geometry={nodes.Cube117.geometry} material={mat} />
      <mesh geometry={nodes.Cube115.geometry} material={mat} />
      <mesh geometry={nodes.Cube114.geometry} material={mat} />
      <mesh geometry={nodes.Cube118.geometry} material={mat} />
      <mesh geometry={nodes.Cube119.geometry} material={mat} />
      <mesh geometry={nodes.Cube120.geometry} material={mat} />
      <mesh geometry={nodes.Cube121.geometry} material={mat} />
      <mesh geometry={nodes.Cube019.geometry} material={mat} />
      <mesh geometry={nodes.Cube022.geometry} material={mat} />
      <mesh geometry={nodes.Cube027.geometry} material={mat} />
      <mesh geometry={nodes.Cube048.geometry} material={mat} />
      <mesh geometry={nodes.Cube049.geometry} material={mat} />
      <mesh geometry={nodes.Cube053.geometry} material={mat} />
      <mesh geometry={nodes.Cube070.geometry} material={mat} />
      <mesh geometry={nodes.Cube071.geometry} material={mat} />
      <mesh geometry={nodes.Cube113.geometry} material={mat} />
      <mesh
        geometry={nodes.Cube102.geometry}
        material={mat}
        position={[-10.16, 0.04, 0]}
        scale={[1, 0.14, 2.99]}
      />
    </group>
  );
}

useGLTF.preload("/dungeon-transformed.glb");
